Func test using imagediff

diff --git a/Bakefile/test/func b/Bakefile/test/func
--- a/Bakefile/test/func
+++ b/Bakefile/test/func
@@ -2,9 +2,20 @@
 
 
 dir=func
+declare -a failed=()
 
 mkdir -p $dir
-ls src/outputs | sed 's/\.js$//g' | while read output; do
+for output in `ls src/outputs | sed 's/\.js$//g'`; do
   bin/image-html -o $output example.png $dir/$output.html
   $BAKE render $dir/$output.html $dir/$output.png
+  # FIXME: use return status once that is fixed
+  status=`node_modules/.bin/imagediff -e example.png $dir/$output.png`
+  if [ "$status" != true ]; then
+    failed=("${failed[@]}" "$output")
+  fi
 done
+
+if [ ${#failed} -ne 0 ]; then
+  echo "Failures: ${failed[@]}" >&2
+  exit 1
+fi
